name: linters
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false  
      - uses: actions/checkout@v3
      
      - name: Run test
        run: go test ./...
      
      - name: Run vet
        run: go vet ./...

      - name: Run Revive linter
        uses: docker://morphy/revive-action:v2